In [1]:
import pandas as pd
import numpy as np

# Read in the data, and fill missing values
data = pd.read_csv("../Data/clean_weather.csv", index_col=0)
data = data.ffill()

data

tmax  tmin  rain  tmax_tomorrow
1970-01-01  60.0  35.0   0.0           52.0
1970-01-02  52.0  39.0   0.0           52.0
1970-01-03  52.0  35.0   0.0           53.0
1970-01-04  53.0  36.0   0.0           52.0
1970-01-05  52.0  35.0   0.0           50.0
...          ...   ...   ...            ...
2022-11-22  62.0  35.0   0.0           67.0
2022-11-23  67.0  38.0   0.0           66.0
2022-11-24  66.0  41.0   0.0           70.0
2022-11-25  70.0  39.0   0.0           62.0
2022-11-26  62.0  41.0   0.0           64.0

[13509 rows x 4 columns]

In [2]:
data['tmax'].head(10)

1970-01-01    60.0
1970-01-02    52.0
1970-01-03    52.0
1970-01-04    53.0
1970-01-05    52.0
1970-01-06    50.0
1970-01-07    52.0
1970-01-08    56.0
1970-01-09    54.0
1970-01-10    57.0
Name: tmax, dtype: float64

In [3]:
data['tmax'].head(10).to_numpy()[np.newaxis, :]

array([[60., 52., 52., 53., 52., 50., 52., 56., 54., 57.]])

In [10]:
# Example of a forward pass
np.random.seed(0)

i_weight = np.random.rand(1,2)
h_weight = np.random.rand(2,2)
o_weight = np.random.rand(2,1)

temps = data['tmax'].tail(3).to_numpy()
temps

array([66., 70., 62.])

In [12]:
x0 = temps[0].reshape(1,1)
x1 = temps[1].reshape(1,1)
x2 = temps[2].reshape(1,1)

array([[36.22169126, 47.20249818]])

### Time step 0

In [22]:
xi_0 = x0 @ i_weight
print(f"xi_0 is {xi_0}")
xh_0 = np.maximum(0, xi_0)
print(f"xh_0 is {xh_0}")
xo_0 = xh_0 @ o_weight
print(f"xo_0 is {xo_0}")

xi_0 is [[36.22169126 47.20249818]]
xh_0 is [[36.22169126 47.20249818]]
xo_0 is [[57.94406231]]


### Time step 1

In [24]:
xi_1 = x1 @ i_weight
print(f"xi_1 is {xi_1}")
xh_1 = np.maximum(0, xh_0 @ h_weight + xi_1)
print(f"xh_1 is {xh_1}")
xo_1 = xh_1 @ o_weight
print(f"xo_1 is {xo_1}")

xi_1 is [[38.41694527 50.06325565]]
xh_1 is [[ 80.24761908 100.28766177]]
xo_1 is [[124.54916092]]


### Time step 2

In [25]:
xi_2 = x2 @ i_weight
print(f"xi_2 is {xi_2}")
xh_2 = np.maximum(0, xh_1 @ h_weight + xi_2)
print(f"xh_2 is {xh_2}")
xo_2 = xh_2 @ o_weight
print(f"xo_2 is {xo_2}")

xi_2 is [[34.02643724 44.34174072]]
xh_2 is [[124.88411227 152.84252918]]
xo_2 is [[190.94853131]]
